import { getCurrentScheme } from "@/utils/colorScheme";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
config.autoAddCss = false;
const inter = Inter({ subsets: ['latin'] })
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const scheme = await getCurrentScheme();
  return (
    <html lang="en" className={scheme === "dark" ? 'dark' : ''}>
      <body className={`${inter.className} h-screen bg-neutral-200 dark:bg-black`}>
        {children}</body>
    </html>
  )
}
