import Providers from "@/providers";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/navbar/NavBar";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { getCurrentScheme } from "@/utils/colorScheme";
import CookieConsent from "@/components/CookieConsent";
import { cookies } from "next/headers";
import UserModal from "@/components/auth/UserModal";
import { auth } from "@/utils/auth";
import { SessionProvider } from "next-auth/react";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <>
      <Providers>
        <NavBar></NavBar> <div className="flex flex-col pt-28 min-h-full">{children}</div>
      </Providers>
      {!cookies().has("cookieConsent") && <CookieConsent></CookieConsent>}
      <UserModal user={session?.user}></UserModal>
    </>
  );
}
