import Providers from '@/providers'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/navbar/NavBar'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { getCurrentScheme } from '@/utils/colorScheme'
import CookieConsent from '@/components/CookieConsent'
import { cookies } from 'next/headers'
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const scheme = await getCurrentScheme();
  return (
    <html lang="en" className={scheme === "dark" ? 'dark' : ''}>
      <body className={`${inter.className} h-screen bg-neutral-200 dark:bg-black`}>
        <Providers>
        <NavBar></NavBar> <div className="mt-28 ">{children}</div>
        </Providers>
        {!cookies().has("cookieConsent") && <CookieConsent></CookieConsent>}

        </body>
    </html>
  )
}
